name: trackassist

description: A new Flutter project.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # flutter_rating_bar: ^4.0.0
  # pdf: ^3.6.0
  #

  open_file: ^3.2.1
  cached_network_image: ^3.2.0
  fluttertoast: 8.0.8
  # google_fonts: ^2.3.1
  date_format: ^2.0.5
  pin_code_fields: 7.3.0
  image_picker: ^0.8.4+7
  image_cropper: 1.4.1
  fab_circular_menu: 1.0.2
  permission_handler: ^8.3.0 # for ios: if using xcode version 11, you must use version 5.0.1+2 without caret symbol (^), but we recomended to using the latest xcode version
  shared_preferences: ^2.0.13
  flutter_local_notifications: ^9.2.0
  image: ^3.1.1
  dio: ^4.0.4
  url_launcher: ^6.0.18
  maps_launcher: ^2.0.1
  uuid: ^3.0.5
  dropdown_search: ^5.0.2
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.7
  firebase_storage: ^10.2.5

  # charts_flutter:
  #   git:
  #     url: git://github.com/google/charts.git
  #     path: charts_flutter
  # intl: 0.17.0
  mask_text_input_formatter: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_spinkit: ^5.1.0
  # provider: ^6.0.1
  line_icons: ^2.0.1
  # whatsapp_unilink: ^2.0.0
  firebase_core: ^1.11.0
  firebase_analytics: ^9.0.5
  # timeago: ^3.1.0
  equatable: ^2.0.3
  easy_mask: ^2.0.1
  flutter_easyloading: ^3.0.3
  firebase_messaging: ^11.2.5
  get: ^4.3.8
  local_auth: ^1.1.8
  font_awesome_flutter: ^9.2.0
  syncfusion_flutter_charts: ^19.3.48
  flutter_svg: ^1.0.3
  step_progress_indicator: ^1.0.1
  im_stepper: ^0.1.3
  universal_io: ^2.0.4
  signature: ^5.0.0
  flutter_auth: ^0.0.1
  flutter_bloc: ^8.0.1
  crypto: ^3.0.1
  searchfield: ^0.6.2
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  video_player: ^2.2.18
  google_maps_flutter: ^2.1.12
  map: ^1.3.3
  rflutter_alert: ^1.0.3
  location: ^4.3.0
  latlng: ^0.2.0
  package_info_plus: ^1.4.0
  swipeable_button_view: ^0.0.2
  page_transition: ^2.0.9

  # auto_size_text: ^3.0.0
  # auto_size_text_field: ^1.0.1
  hive: ^2.1.0
  slider_button: ^2.0.0
  flutter_html: ^3.0.0-alpha.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icons/tato_icon.png"

flutter:
  uses-material-design: true

  # fonts:
  #   - family: UniviaPro
  #     fonts:
  #       - asset: assets/fonts/UniviaPro-Regular.otf
